--VISTA EN DONDE SE MUESTRAN SOLO LOS REGISTROS LLAMADOS POR EL ID QUE SE ENCUENTRAN ACTIVOS EN LA TABLA "AULA"
CREATE VIEW vw_Aula_SeleccionarUnRegistroPorId AS SELECT * FROM Aula WHERE NumeroAula = '3_2'
and activo =1