--VISTA EN DONDE SE MUESTRAN SOLO LOS REGISTROS LLAMADOS POR EL ID QUE SE ENCUENTRAN ACTIVOS EN LA TABLA "CURSOS"
CREATE VIEW vw_Cursos_SeleccionarUnRegistroPorId AS SELECT * FROM Cursos WHERE CodigoCurso = 'A4352'
and activo =1