--VISTA EN DONDE SE MUESTRAN SOLO LOS REGISTROS LLAMADOS POR EL ID QUE SE ENCUENTRAN ACTIVOS EN LA TABLA "MATRICULA"
CREATE VIEW vw_Matricula_SeleccionarUnRegistroPorId AS SELECT * FROM Matricula WHERE CedulaEstudiante = '5-09480567'
and activo =1