--VISTA EN DONDE SE MUESTRAN SOLO LOS REGISTROS LLAMADOS POR EL ID QUE SE ENCUENTRAN ACTIVOS EN LA TABLA "UNIVERSIDAD"
CREATE VIEW vw_Universidad_SeleccionarUnRegistroPorId AS SELECT * FROM Universidades WHERE CodigoUniversidad = 2
and activo =1